apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deploy
  labels:
    app: zookeeper-1
spec:
  selector:
    matchLabels:
      app: zookeeper-1
  replicas: 2  
  template:
    metadata:
      labels:
        app: zookeeper-1        
    spec:
      containers:
        - name: zoo1
          image: digitalwonderland/zookeeper
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_ID
              value: "1"              
            - name: ZOOKEEPER_SERVER_1
              value: zoo1